# Generated by Django 2.0.5 on 2019-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/avatar/default_avatar.jpg', upload_to='users/avatar/%Y/%m', verbose_name='头像'),
        ),
    ]
