# Generated by Django 2.0.5 on 2019-11-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='个人描述'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='个人主页'),
        ),
    ]
